name: Trigger Remote Workflow
permissions: write-all
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  trigger:
    name: Trigger workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check Latest Workflow Run Status
        id: check-latest-run-1
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const ownerRepo = `BoscoFZ`;
            const repoName = `makeshortuserscript`;
            const completedRuns = await github.rest.actions.listWorkflowRuns({
              owner: ownerRepo,
              repo: repoName,
              workflow_id: 'convert.yml',
              status: 'completed',
              per_page: 1
            });
            const runningRuns = await github.rest.actions.listWorkflowRuns({
              owner: ownerRepo,
              repo: repoName,
              workflow_id: 'convert.yml',
              status: 'in_progress',
              per_page: 1
            });
            const hasCompletedRunFailed = completedRuns.data.workflow_runs.length > 0 && completedRuns.data.workflow_runs[0].conclusion !== 'success';
            const hasRunningJobs = runningRuns.data.workflow_runs.length > 0;
            if(hasCompletedRunFailed || hasRunningJobs) {
              core.setOutput('run_next_workflow1', 'false');
              core.setFailed('A job is currently running, or the last completed workflow run failed.');
            } else {
              core.setOutput('run_next_workflow1', 'true');
            }
      - name: Trigger the Workflow
        if: ${{ steps.check-latest-run-1.outputs.run_next_workflow1 == 'true' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: "BoscoFZ",
              repo: "makeshortuserscript",
              workflow_id: "convert.yml",
              ref: "main"
            })
